### ISSUE TITLE
Getting OCI Run time error - when i tried to run your project inside docker

### ISSUE THREAD

**Issue by anil8040** [serbanghita/wdio5-docker#1]
Hi  I am working on running automation scripts using webdriverio inside docker 

While i tried to run your project inside the docker ,i am getting 
OCI Runtime error (Not sure if i need to make any update in running inside the docker)
Can you please help me regarding this

![OCIError](https://user-images.githubusercontent.com/48579523/56465737-c15eac80-63d2-11e9-8161-07a25e9ef9ef.jpg)

**Comment by serbanghita** [comment]
@anil8040 looks like a Docker specific error, see https://github.com/docker/compose/issues/4039
I never had this issue before. What is your OS?

**Comment by anil8040** [comment]
Hi ,
Its Windows 10 Machine, Docker running on linux server

**Comment by serbanghita** [comment]
`uname -a` was useful on the linux machine

**Comment by serbanghita** [comment]
Btw make sure you are using the Dockerfile image from `docker/Dockerfile`, not the one from root (that one I will delete because it's obsolete)

See https://github.com/vvo/selenium-standalone/tree/master/docker

**Comment by anil8040** [comment]
I used the docker file as specified But still getting the same error
Where do we need to add uname -a
